name: Run doc build and create artifact

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - "runci/**"
  schedule:
    # 04:00 every Tuesday morning
    - cron: "0 4 * * 2"

jobs:
  docs-checks:
    name: Run doc build and create artifact 
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: '0'
        submodules: true
    - name: Set up Python 3.10
      if: github.event_name == 'push' || github.event_name == 'schedule'
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install poetry
      run: pip install poetry
    - name: Install extension
      run: |
        poetry install --no-root
    - name: Install docs dependencies
      run: |
        cd docs && bash ./install.sh
    - name: Build docs
      timeout-minutes: 20
      run: |
        cd docs && poetry run bash ./build-docs.sh
    - uses: actions/upload-artifact@v4
      if: github.event_name == 'release' || contains(github.ref, 'refs/heads/wheel')
      with:
        name: docs
        path: docs/build/
