name: Release

on:
  push:
    branches:
      - "wheel/**"
  release:
    types:
      - created
      - edited

jobs:
  build-and-publish:
    name: Build, test, and store artifact, and upload to pypi
    uses: CQCL/pytket-braket/.github/workflows/release-wf.yml@infra/uv-and-workflows
    with:
      pyver: "3.10"
      publish: ${{ github.event_name == 'release' }}
    secrets:
      PYPI_API_TOKEN: ${{ secrets.PYPI_PYTKET_BRAKET_API_TOKEN }}
